### ISSUE TITLE
Moving dots with lines in between

### ISSUE THREAD

**Issue by Thanmai-C** [adorableio/react-native-animated-ellipsis#7]
Hi,
Please can u help me to do the below:
https://i.stack.imgur.com/6OJaG.png

I just need like when i click on a button the line show proceed to next dot.(the color of dots and line moving should be colored)
I am asking you as this library looks similar,so could you further extend and help me.

**Comment by bigtiger** [comment]
@Thanmai-C The author of this library is unavailable as they are on vacation for two weeks. Additionally, your request seems beyond the scope of this library.

**Comment by bigtiger** [comment]
@Thanmai-C I believe this library will accomplish what you're the effect you desire: https://github.com/24ark/react-native-step-indicator
